import { Sora } from "next/font/google";
import "./globals.css";
import Navbar from "./components/navbar"; 
import Footer from "./components/Footer";
const sora = Sora({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-sora",
});

export const metadata = {
  title: "Ayoub DEV",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="fr" className={sora.className}>
      <body>
        <Navbar />
        {children}
        <Footer/>
      </body>
    </html>
  );
}
